language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
script: pytest --cov=Yinotify tests/
after_success:
  - coveralls
